#!/bin/bash
# Quick Docker Commands - Copy and paste these one at a time

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐳 Docker Commands for LLM Assessment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login to Docker Hub:"
echo "   docker login"
echo ""
echo "2. Build the image:"
echo "   docker build -t hashdev89/llmassesment:latest ."
echo ""
echo "3. Push to Docker Hub:"
echo "   docker push hashdev89/llmassesment:latest"
echo ""
echo "4. Or use the script:"
echo "   ./build-and-push.sh latest"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
